server:
  port: 3001

spring:
  application:
    name: ideasy_server
  # 数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.100:3306/ideasy?useUnicode=true&characterEncoding=UTF-8?useSSL=false
      username: root
      password: Libin704098.00

# 开启日志
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG

# MyBatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml # classpath: ==> resources/
  type-aliases-package: com.triable.ideasy_server.pojo # 包别名
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
